### ISSUE TITLE
"Player not found" for existing Player

### ISSUE THREAD

**Issue by ToasterUwU** [Domekologe/ow-api#1]
Hey, first of all, thanks for making an up to date fork.

I was using a closed-source fork before, but that one keeps breaking, and the creator doesn't want you to ping them or anything, so you need to pray that they will help you if you have issues. So an actual Github page like here is way more nice. Thanks a lot.

My issue is that a person who has made their profile public more than a day ago is still shown as "Player not found" when trying to find them.

Here is the page that shows that, in fact, they are public: https://overwatch.blizzard.com/en-us/career/Silverhand-21270/
Neither their PC stats, nor Xbox stats are able to be accessed via the API. And since you are using Cloudflare, maybe this is a caching issue or something like that.

Anyways, would be really nice if we can take a look together and figure this issue out. I would love to switch to this fork for my Overwatch Discord Bot

**Comment by ToasterUwU** [comment]
I just noticed that you link to the maintainer of the closed-source version im using right now in your Funding.yml, and now im confused... Would be cool if you could explain that to me, im kinda confused about that and curious

**Comment by ToasterUwU** [comment]
I did a little debugging myself, and it looks like https://github.com/Domekologe/ow-api/blob/9aa50dd18aa44b0fd9620a65874fe7a1f8cb6235/ovrstat/player_stats.go#L292 is the issue, at least part of it.
The URL it builds itself and uses is https://overwatch.blizzard.com/en-us/search/account-by-name/Silverhand%2321270 which isn't the URL to get the data, https://overwatch.blizzard.com/en-us/search/account-by-name/Silverhand#21270 is. If used in the browser, it will redirect to https://overwatch.blizzard.com/en-us/search/account-by-name/Silverhand/#21270.

To get the right URL in this specific case (wont work for other cases most likely), I just removed the url.PathEscape function and used the raw value.

With the correct data, there are lots of results for the name, but another issue remains. The resulting data is as empty as possible: 
```go
{"icon":"","name":"","endorsement":0,"endorsementIcon":"","title":"","ratings":null,"private":true}
```

**Comment by ToasterUwU** [comment]
Found the reason for that as well.

The code just takes the first entry, even if its the wrong one. In this case, the right one is there, but its like entry 35, its very likely because the changes i made, but entry 35 is definitely better and closer than no entries being found at all.
https://github.com/Domekologe/ow-api/blob/9aa50dd18aa44b0fd9620a65874fe7a1f8cb6235/ovrstat/player_stats.go#L194
If i overwrite the value before the check, to force it to be like the one of the wanted profile, i get `{"message":"Failed to retrieve player stats: Invalid platform"}` for platform being "xbl", that might be because it changed to be PC and Console only on the website this is scraping, so maybe i need to enter something else then XBL, PSN, etc., but i don't know what it would be, "console" also throws the same error.

**Comment by Domekologe** [comment]
Hi,

glad you figured out what was the issue. I am also very new in golang and the begin part to check how this code works was hard for me. 
I didn't had any issues with names in my tests, but nice to know there was issues and they are fixed now.
For the Fundings,yml file.. I never really checked this file tbh

I found the files first in another repository (which was an fork of the original), but after I wanted to make a fork of them, I wasn't able to find it again and decided to use the original one and only overwrite the files. 
After that I added changes to make it functional again for newer base of Overwatch 2 Profile site

**Comment by ToasterUwU** [comment]
@Domekologe I see, you probably found the one I used before, I couldn't find the source of that one... So yeah.

Happy this helps, are you gonna update the online version as well? Im gonna stick with the local instance I set up 10 minutes ago, but still wanna make sure the public instance is up to date

**Comment by tystuyfzand** [comment]
> Hi,
> 
> glad you figured out what was the issue. I am also very new in golang and the begin part to check how this code works was hard for me. I didn't had any issues with names in my tests, but nice to know there was issues and they are fixed now. For the Fundings,yml file.. I never really checked this file tbh
> 
> I found the files first in another repository (which was an fork of the original), but after I wanted to make a fork of them, I wasn't able to find it again and decided to use the original one and only overwrite the files. After that I added changes to make it functional again for newer base of Overwatch 2 Profile site

Original fork is https://github.com/ow-api/ovrstat - it's what the hosted site uses too, no hidden secrets here :)

**Comment by ToasterUwU** [comment]
I see, I assumed the server would look at the data behind # as well, since it technically can.

Anyways, I think it's better to search for just the name always like it is right now, this way its only one request instead of potentially 2. And even for simple names like Silverhand there are only a handful of people that are returned.
